name: Manual-Trigger-Example  # Name of the Pipeline 

# Manual Run The Pipeline
on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  azure-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Login
        uses: Azure/login@v1.5.1
        with:
          creds: ${{ secrets.GITHUBACTION_SPN }}
