name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
