name: Manual-Trigger-Example  # Name of the Pipeline 

# Manual Run The Pipeline
on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests..."

  Azure:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: 'Log into Azure using github secret GITHUBACTION_SPN'
        uses: Azure/login@v1.5.1 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # This references the secret you created earlier
          enable-AzPSSession: true # This enables the Az Powershell session
