name: Manual-Trigger-Example  # Name of the Pipeline 

# Manual Run The Pipeline
on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a      
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "second job."

  Azure:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Create Azure Credentials JSON
        run: |
          echo '{
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }' > azure_creds.json

      - name: Login to Azure
        run: |
          az login --service-principal -u $(jq -r .clientId azure_creds.json) -p $(jq -r .clientSecret azure_creds.json) --tenant $(jq -r .tenantId azure_creds.json)

      - name: List Resource Groups
        run: |
          az group list --output table