name: Manual-Trigger-Example  # Name of the Pipeline 

# Manual Run The Pipeline
on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  azure-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" | az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p - --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Execute Azure CLI Command
        run: |
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          # Replace the following command with your desired Azure CLI command
          az group list
