name: Manual-Trigger-Example  # Name of the Pipeline 

# Manual Run The Pipeline
on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a      
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "second job."

  Azure:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure@v1
        with:
          azure-cli-version: 'latest'

      - name: Login to Azure
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
          az login --service-principal --username $(jq -r .clientId azure_creds.json) --password $(jq -r .clientSecret azure_creds.json) --tenant $(jq -r .tenantId azure_creds.json)

      - name: List Resource Groups
        run: |
          az group list --output table
