name: Manual-Trigger-Example  # Name of the Pipeline 

# Manual Run The Pipeline
on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a      
      - name: Echo input
        run: echo "Input value is ${{ github.event.inputs.exampleInput }}"
      - name: Echo input
        run: echo "Last Output"
      - name: Echo last after
        run: uname -a
  test:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "second job."
